= Data4Life Auth SDK
:link-repository: https://github.com/d4l-data4life/hc-auth-sdk-kmp
:project-version: 1.16.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p><!-- PROJECT LOGO -->
        <a href="https://github.com/d4l-data4life/hc-auth-sdk-kmp">
            <img src="assets/images/d4l-logo.svg" width="150"/>
        </a>
    </p>
    <p><!-- PROJECT TITLE -->
        <h3>Data4Life Auth SDK</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        Authorization SDK for communicating with PHDC using OAuth 2.0
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/d4l-data4life/hc-auth-sdk-kmp/issues">Report Bug</a>
        ·
        <a href="https://github.com/d4l-data4life/hc-auth-sdk-kmp/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/d4l-data4life/hc-auth-sdk-kmp/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a href="https://github.com/d4l-data4life/hc-auth-sdk-kmp/actions">
            <img src="https://github.com/d4l-data4life/hc-auth-sdk-kmp/actions/workflows/d4l-ci-latest-version.yml/badge.svg" alt="D4L CI - Latest Version"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents

toc::[]

== About The Project

Authorization SDK for communicating with PHDC using link:https://tools.ietf.org/html/rfc6749[OAuth 2.0]. For Android it implements link:https://tools.ietf.org/html/rfc8252[RFC 8252 - OAuth 2.0 for Native Apps] using link:https://github.com/openid/AppAuth-Android[AppAuth]. Java is supporting the OAuth 2.0 Code Grant using link:https://github.com/scribejava/scribejava[ScribeJava].

=== Features

* Android: OAuth 2.0 - Native App flow
* Java: OAuth 2.0 - Code Grant flow

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]

== Getting Started

Instructions how to get software up and running.

=== Prerequisites

* link:https://developer.android.com/studio#downloads[Android Studio - Chipmunk - 2021.2.1]
* link:https://adoptopenjdk.net/[Java 11] | link:https://developer.android.com/studio/write/java8-support[Limitations of Java language features and APIs] | https://jakewharton.com/d8-library-desugaring/[Desugaring]
* link:https://kotlinlang.org/[Kotlin 1.6.21]
* Android 6.0 (API 23) to Android 11.0 (API 31)

=== Installation

A step by step series of examples that tell you how to get it running.

==== Consume GitHub Packages

We use GitHub Packages to distribute the SDK. In order to consume our dependencies you need to generate a GitHub Personal Access Token. Please follow the how to link:https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages#authenticating-to-github-packages[authenticate to GitHub Packages, window="_blank"].

NOTICE:: You need to have _read_ access to this repository and generate a https://github.com/settings/tokens/new/[personal access token] with `repo` and `read:packages` scope.

===== Token

The token needs to be made available.

. Add `gpr.user = {GitHub username}` and `gpr.key = {GitHub Personal Access Token}` to your global Gradle properties `~/.gradle/gradle.properties`

    gpr.user=github-username
    gpr.key=github-token

. Or add following environment variables `PACKAGE_REGISTRY_USERNAME={GitHub username}` and `PACKAGE_REGISTRY_TOKEN={GitHub Personal Access Token}`

===== Setup Maven Repository

Add the following maven repository configuration to your root build.gradle:

[source, Gradle]
----
    allprojects {
        repositories {
            ...
            maven {
                url = URI("https://maven.pkg.github.com/d4l-data4life/hc-auth-sdk-kmp")
                credentials {
                    username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                    password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
                }
            }
        }
    }
----

==== Java

Add following dependencies to your app build.gradle.

----
dependencies {
    implementation "care.data4life.hc-auth-sdk-kmp:auth-jvm:$version"
}
----

==== Android

----
dependencies {
    implementation "care.data4life.hc-auth-sdk-kmp:auth-android:$version"
}
----

In case you target Android 11+ and experience a `ActivityNotFoundException`. This is caused by the changed link:https://developer.android.com/about/versions/11/privacy/package-visibility[package visibility in Android 11]. Please ensure that the following is part of your merged `AndroidManifest.xml`. In case not, add the following to your `AndroidManifest.xml` file:

----
<manifest>
    <application>
        ...
    </application>

    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>

</manifest>
----

== Usage

The authorization request is started with the following code sample which launches an link:https://developer.chrome.com/docs/android/custom-tabs/[Custom Tab]
to present the login screen to the user for authentication.

[source]
----
Intent authIntent = Data4LifeClient.getInstance().getLoginIntent(null);
startActivityForResult(authIntent,requestCode);
----

Once the user finished, canceled or an error occurred during the browser login, the SDK sends the response to the
integrator application in the `onActivityResult(…)` method.

The authorization results can be the following:

- `Activity.RESULT_OK` – when the login is successful.
- `Activity.RESULT_CANCELED` – when the login fails, with additional payload in `data`, as shown in the example.

To end the login you need to call `finishLogin(authData, callback)` with the intent received in `onActivityResult(…)`.
The callback will indicate if the authorization successfully finished.

[source]
----
@Override protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);
    if (requestCode == GC_AUTH) {
        if (resultCode == RESULT_OK) {
            client.finishLogin(data,callback);
        } else if (data.getExtras() != null) {
            if (data.getExtras().containsKey("error")) {
                Snackbar.make(mRootCL, "Failed to log in to Data4Life", Snackbar.LENGTH_SHORT).show();
            } else if (data.getExtras().containsKey("canceled")) {
                Snackbar.make(mRootCL, "User canceled authorization request", Snackbar.LENGTH_SHORT).show();
            }
        }
    }
}
----

== Roadmap

This project is work in progress. We are working on adding more functionality, guidelines, documentation and other improvements.

Also see the open link:{link-repository}/issues[issues] for a list of proposed features and known issues.

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.
* link:DEVELOPING.adoc[Developing] for details about our development process and how to build and test the project.

== Copyright and License

Copyright (c) 2021 D4L data4life gGmbH / All rights reserved.

Please refer to our link:LICENSE[License] for further details.
